apiVersion: v1
kind: Namespace
metadata:
  name: ns-energy-europe

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-pod
  namespace: ns-energy-europe

spec:
  selector:
    matchLabels:
      app: energy # Selector for pod name search. Use -l flag with kubectl.

  template:
    metadata:
      labels:
        app: energy

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: energy-api
          image: service-image
          imagePullPolicy: Never #if this is not defined, then k8 tries to find the image in the docker registry and it fails

          ports:
            - name: energy-api
              containerPort: 6000
          env:
#            This sets the value of GOMAXPROCS to whatever the value of limits.cpu is inside infra/k8s/patch-deploy.yaml, which is 1
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu

---

apiVersion: v1
kind: Service
metadata:
  name: energy-api
  namespace: ns-energy-europe

spec:
  selector:
    app: energy
