apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base.yaml
patches:
  - path: ./patch-deploy.yaml
  - path: ./patch-service.yaml
images:
  - name: service-image
    newName: giou/energy-service/energy-api
    newTag: "0.2"
