apiVersion: v1
kind: Service
metadata:
  name: energy-api
  namespace: ns-energy-europe

spec:
  type: ClusterIP

  ports:
    - name: energy-api
      port: 3000
      targetPort: energy-api
    - name: energy-debug
      port: 3011
      targetPort: energy-debug